version: "3.7"
services:
  devenv:
    container_name: devenv
    image: jmera/devenv:latest
    stdin_open: true
    tty: true
    volumes:
      - .:/home/dev/workspace/devenv/:delegated
      - workspace:/home/dev/workspace/
    working_dir: /home/dev/workspace/

volumes:
  workspace:
