version: "3.7"
services:
  devenv:
    image: devenv
    build:
      context: .
    container_name: devenv
    volumes:
      - workspace:/home/dev/workspace/
    stdin_open: true
    tty: true

volumes:
  workspace:
