version: "3.7"
services:
  devenv:
    image: jmera/devenv
    container_name: devenv
    stdin_open: true
    tty: true
    volumes:
      - workspace:/home/dev/workspace/
    working_dir: /home/dev/workspace/

volumes:
  workspace:
