version: "3.7"
services:
  devenv:
    image: devenv
    build:
      context: .
    container_name: devenv
    environment:
      - LC_ALL="en_US.UTF-8"
    volumes:
      - home:/home/dev/
      - workspace:/home/dev/workspace/
    working_dir: /home/dev/workspace/
    command: tmux
    stdin_open: true
    tty: true

volumes:
  home:
  workspace:
