version: "3.7"
services:
  devenv:
    image: jmera/devenv:latest
    container_name: devenv
    volumes:
      - workspace:/home/dev/workspace/
      - .:/home/dev/workspace/devenv/:delegated
    working_dir: /home/dev/workspace/

volumes:
  workspace:
